# Generated by Django 4.2.7 on 2024-01-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeebooking',
            name='booking_status',
            field=models.CharField(choices=[('pending', 'pending'), ('ongoing', 'ongoing'), ('completed', 'completed')], default='pending', max_length=30),
        ),
    ]
