# Generated by Django 4.2.7 on 2024-01-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employeeabsence'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeebooking',
            name='is_review',
            field=models.BooleanField(default=True),
        ),
    ]
