# Generated by Django 4.2.7 on 2024-01-24 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
