# Generated by Django 4.2.7 on 2024-01-25 13:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0008_alter_review_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('employee', 'user')},
        ),
    ]
