# Generated by Django 4.2.7 on 2023-11-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_setup', '0004_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='charge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='place',
            field=models.CharField(default='Unknown', max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='work',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='EmployeeDetail',
        ),
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
