# Generated by Django 4.2.7 on 2023-12-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_setup', '0006_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='charge',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='experience',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='place',
            field=models.CharField(blank=True, default='Unknown', max_length=150, null=True),
        ),
    ]
