# Generated by Django 4.2.7 on 2023-12-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_setup', '0007_alter_user_charge_alter_user_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='charge',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
