# Generated by Django 4.2.7 on 2023-12-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_setup', '0008_alter_user_charge_alter_user_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='Service_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile'),
        ),
    ]
