# Generated by Django 4.2.7 on 2023-12-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_setup', '0013_servicecategory_alter_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
