# Generated by Django 4.2.7 on 2023-12-24 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_setup', '0015_availableday_employeeavailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBookedDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_setup.availableday')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
