# Generated by Django 4.2.7 on 2024-01-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_setup', '0018_weeklyavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeebooking',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeebooking',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='WeeklyAvailability',
        ),
    ]
